/**
 * Markdown node generator - creates human and AI readable node summaries
 */

import * as fs from 'fs/promises';
import * as path from 'path';
import { FileNode, MarkdownNode } from '../../shared/types.js';

// Markdown nodes directory
const MARKDOWN_NODES_DIR = process.env.MARKDOWN_NODES_DIR || './markdown-nodes';

/**
 * Initialize markdown nodes directory
 */
export async function initMarkdownNodes(): Promise<void> {
  try {
    await fs.mkdir(MARKDOWN_NODES_DIR, { recursive: true });
    console.log(`✓ Markdown nodes directory: ${MARKDOWN_NODES_DIR}`);
  } catch (error) {
    console.error('Failed to create markdown nodes directory:', error);
    throw error;
  }
}

/**
 * Generate Markdown summaries for all nodes
 */
export async function generateMarkdownNodes(nodes: FileNode[]): Promise<void> {
  console.log('Generating Markdown nodes...');

  // Initialize directory
  await initMarkdownNodes();

  // Generate markdown for each node
  for (const node of nodes) {
    await generateMarkdownNode(node);
  }

  console.log(`✓ Generated Markdown for ${nodes.length} nodes`);
}

/**
 * Generate Markdown summary for a single node
 */
async function generateMarkdownNode(node: FileNode): Promise<void> {
  const markdown = createMarkdownContent(node);

  // Create file path
  const fileName = `${node.id}.md`;
  const filePath = path.join(MARKDOWN_NODES_DIR, fileName);

  // Write markdown file
  await fs.writeFile(filePath, markdown, 'utf-8');
}

/**
 * Create Markdown content for a node
 */
function createMarkdownContent(node: FileNode): string {
  const tags = generateTags(node);
  const inferredPurpose = inferPurpose(node);

  return `# Node: ${node.name}

## Path
\`${node.path}\`

## Type
${node.type === 'directory' ? 'Directory' : 'File'}${node.extension ? ` (${node.extension})` : ''}

## Properties
- **Size**: ${formatSize(node.size)}
- **Created**: ${formatDate(node.createdAt)}
- **Modified**: ${formatDate(node.modifiedAt)}
- **Depth**: ${node.depth}

## Inferred Purpose
${inferredPurpose}

## Tags
${tags.map(tag => `\`${tag}\``).join(', ')}

## Quick Access
→ Load content (on-demand)
→ View in graph

---
*Generated by Local Knowledge Graph*
`;
}

/**
 * Generate tags for a node based on its properties
 */
function generateTags(node: FileNode): string[] {
  const tags: string[] = [];

  // Type tag
  tags.push(node.type);

  // Extension tag
  if (node.extension) {
    const ext = node.extension.replace('.', '');
    tags.push(ext);

    // Language specific tags
    const languageMap: Record<string, string> = {
      '.ts': 'typescript',
      '.js': 'javascript',
      '.py': 'python',
      '.rs': 'rust',
      '.go': 'go',
      '.java': 'java',
      '.md': 'markdown',
      '.txt': 'text',
      '.json': 'json',
      '.yaml': 'yaml',
      '.yml': 'yaml',
    };

    if (languageMap[node.extension]) {
      tags.push(languageMap[node.extension]);
    }
  }

  // Depth tag (root, mid, leaf)
  if (node.depth === 0) {
    tags.push('root');
  } else if (node.depth < 3) {
    tags.push('top-level');
  } else {
    tags.push('deep');
  }

  return tags;
}

/**
 * Infer purpose of a node based on its properties
 */
function inferPurpose(node: FileNode): string {
  const name = node.name.toLowerCase();
  const path = node.path.toLowerCase();

  // Directories
  if (node.type === 'directory') {
    if (name.includes('test')) {
      return 'Test directory containing test files and test utilities';
    }
    if (name.includes('src') || name.includes('source')) {
      return 'Source code directory containing main application files';
    }
    if (name.includes('lib') || name.includes('library')) {
      return 'Library directory containing reusable code modules';
    }
    if (name.includes('docs') || name.includes('documentation')) {
      return 'Documentation directory with project documentation';
    }
    if (name.includes('config') || name.includes('configuration')) {
      return 'Configuration directory with config files';
    }
    return 'Directory containing related files and subdirectories';
  }

  // Files by extension
  if (node.extension === '.ts' || node.extension === '.js') {
    if (name.includes('test') || name.includes('spec')) {
      return 'Test file testing specific functionality';
    }
    if (name.includes('index')) {
      return 'Entry point or module export file';
    }
    if (name.includes('config') || name.includes('settings')) {
      return 'Configuration file with settings and preferences';
    }
    if (name.includes('util') || name.includes('helper')) {
      return 'Utility or helper function file';
    }
    return 'Source code file implementing application logic';
  }

  if (node.extension === '.md') {
    if (name.toLowerCase() === 'readme.md') {
      return 'Project README with documentation and usage instructions';
    }
    return 'Markdown documentation or notes file';
  }

  if (node.extension === '.json') {
    if (name.includes('package')) {
      return 'Package configuration file (NPM)';
    }
    if (name.includes('tsconfig')) {
      return 'TypeScript configuration file';
    }
    return 'JSON data or configuration file';
  }

  // Generic purpose
  return 'File of type ' + (node.extension || 'unknown');
}

/**
 * Format file size for display
 */
function formatSize(size?: number): string {
  if (!size) return 'N/A';

  const units = ['B', 'KB', 'MB', 'GB'];
  let unitIndex = 0;

  while (size >= 1024 && unitIndex < units.length - 1) {
    size /= 1024;
    unitIndex++;
  }

  return `${size.toFixed(1)} ${units[unitIndex]}`;
}

/**
 * Format date for display
 */
function formatDate(date: Date): string {
  return date.toISOString().split('T')[0];
}

/**
 * Get markdown node content
 */
export async function getMarkdownNode(nodeId: string): Promise<MarkdownNode | null> {
  try {
    const fileName = `${nodeId}.md`;
    const filePath = path.join(MARKDOWN_NODES_DIR, fileName);

    const content = await fs.readFile(filePath, 'utf-8');

    return {
      id: nodeId,
      filePath,
      summary: content,
      tags: [],
      inferredPurpose: '',
      relationships: [],
      quickAccess: {
        loadContentPath: '', // TODO: Load from file
      },
      generatedAt: new Date(),
    };
  } catch (error) {
    return null;
  }
}

/**
 * Delete markdown node
 */
export async function deleteMarkdownNode(nodeId: string): Promise<void> {
  try {
    const fileName = `${nodeId}.md`;
    const filePath = path.join(MARKDOWN_NODES_DIR, fileName);

    await fs.unlink(filePath);
  } catch (error) {
    console.error('Failed to delete markdown node:', error);
  }
}
